<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">booleanToString</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpib29sZWFuIGJQcmVzZW50ID0gZmFsc2U7DQpTdHJpbmcgYlN0cmluZyA9IG51bGw7
DQpPYmplY3QgYkphdmEgPSBudWxsOw0KaWYgKGJQcmVzZW50ID0gcGlwZWxpbmVDdXJzb3IuZmly
c3QoImJKYXZhIikpIHsNCgliSmF2YSA9IElEYXRhVXRpbC5nZXQocGlwZWxpbmVDdXJzb3IsICJi
SmF2YSIpOw0KfQ0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQovLyBwaXBlbGluZQ0KaWYg
KGJQcmVzZW50KSB7DQoJaWYgKG51bGwgIT0gYkphdmEpDQoJCWlmIChiSmF2YSBpbnN0YW5jZW9m
IGphdmEubGFuZy5Cb29sZWFuKQ0KCQkJYlN0cmluZyA9IGJKYXZhLnRvU3RyaW5nKCk7DQoJCWVs
c2UNCgkJCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJSZWNlaXZlZCBvYmplY3QgaXMgbm90
IGEgamF2YS5sYW5nLkJvb2xlYW4hIik7DQoJSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9
IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KCUlEYXRhVXRpbC5wdXQocGlwZWxpbmVDdXJzb3JfMSwg
ImJTdHJpbmciLCBiU3RyaW5nKTsNCglwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTsNCn0=</value>
</Values>
