<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">objectInspect</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsNCmJvb2xlYW4gYlByZXNlbnQgPSBwaXBlbGluZUN1cnNvci5maXJzdCgib2JqZWN0
VG9JbnNwZWN0Iik7DQpPYmplY3QJb2JqZWN0VG9JbnNwZWN0ID0gbnVsbDsNCmlmKGJQcmVzZW50
KSANCglvYmplY3RUb0luc3BlY3QgPSBwaXBlbGluZUN1cnNvci5nZXRWYWx1ZSgpOw0KcGlwZWxp
bmVDdXJzb3IuZGVzdHJveSgpOw0KDQpTdHJpbmcgY2xhc3NOYW1lID0gbnVsbD09b2JqZWN0VG9J
bnNwZWN0PyJudWxsIjpvYmplY3RUb0luc3BlY3QuZ2V0Q2xhc3MoKS5nZXRDYW5vbmljYWxOYW1l
KCk7DQovLyBwaXBlbGluZQ0KcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsN
CklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yLCAicHJlc2VudCIsICIiK2JQcmVzZW50ICk7
DQpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvciwgImNsYXNzIiwgY2xhc3NOYW1lICk7DQpp
ZihudWxsICE9IG9iamVjdFRvSW5zcGVjdCkNCglJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNv
ciwgInRvU3RyaW5nIiwgb2JqZWN0VG9JbnNwZWN0LnRvU3RyaW5nKCkgKTsNCnBpcGVsaW5lQ3Vy
c29yLmRlc3Ryb3koKTsNCg==</value>
</Values>
