<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getSysProp</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsNClN0cmluZwlpblByb3BlcnR5TmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBp
cGVsaW5lQ3Vyc29yLCAiaW5Qcm9wZXJ0eU5hbWUiICk7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95
KCk7DQoNCg0KU3RyaW5nIHJldFZhbHVlID0gU3lzdGVtLmdldFByb3BlcnR5KGluUHJvcGVydHlO
YW1lKTsNCg0KLy8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBl
bGluZS5nZXRDdXJzb3IoKTsNCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJyZXRW
YWx1ZSIsIHJldFZhbHVlKTsNCnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOw0K</value>
</Values>
