<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">checkGlobalVariable</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpTdHJpbmcJaW5WYXJpYWJsZU5hbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBl
bGluZUN1cnNvciwgImluVmFyaWFibGVOYW1lIiApOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgp
Ow0KDQpTdHJpbmcgcmV0RXhpc3RzID0gImZhbHNlIjsNCkdsb2JhbFZhcmlhYmxlc01hbmFnZXIg
Z2xvYmFsVmFyaWFibGVzTWFuYWdlciA9ICBHbG9iYWxWYXJpYWJsZXNNYW5hZ2VyLmdldEluc3Rh
bmNlKCk7DQppZiAoZ2xvYmFsVmFyaWFibGVzTWFuYWdlci5nbG9iYWxWYXJpYWJsZUV4aXN0cyhp
blZhcmlhYmxlTmFtZSkpDQp7DQoJcmV0RXhpc3RzID0gInRydWUiOw0KfQ0KDQovLyBwaXBlbGlu
ZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0K
SURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgInJldEV4aXN0cyIsIHJldEV4aXN0cyk7
DQpwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTsNCgk=</value>
</Values>
