<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">removeGlobalVariableValue</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpTdHJpbmcJaW5WYXJpYWJsZU5hbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBl
bGluZUN1cnNvciwgImluVmFyaWFibGVOYW1lIiApOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgp
Ow0KDQpHbG9iYWxWYXJpYWJsZXNNYW5hZ2VyIGdsb2JhbFZhcmlhYmxlc01hbmFnZXIgPSAgR2xv
YmFsVmFyaWFibGVzTWFuYWdlci5nZXRJbnN0YW5jZSgpOw0KdHJ5IHsNCglpZiAoZ2xvYmFsVmFy
aWFibGVzTWFuYWdlci5nbG9iYWxWYXJpYWJsZUV4aXN0cyhpblZhcmlhYmxlTmFtZSkpDQoJCWds
b2JhbFZhcmlhYmxlc01hbmFnZXIucmVtb3ZlR2xvYmFsVmFyaWFibGUoaW5WYXJpYWJsZU5hbWUp
Ow0KCQ0KfSBjYXRjaCAoR2xvYmFsVmFyaWFibGVzRXhjZXB0aW9uIGUpIHsNCgl0aHJvdyBuZXcg
U2VydmljZUV4Y2VwdGlvbihlLmdldE1lc3NhZ2UoKSk7DQp9IGNhdGNoIChQYXNzd29yZE1hbmFn
ZXJFeGNlcHRpb24gZSkgew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUuZ2V0TWVzc2Fn
ZSgpKTsNCn0gY2F0Y2ggKElPRXhjZXB0aW9uIGUpIHsNCgl0aHJvdyBuZXcgU2VydmljZUV4Y2Vw
dGlvbihlLmdldE1lc3NhZ2UoKSk7DQp9DQoNCi8vIHBpcGVsaW5lDQoJ</value>
</Values>
